<a href="https://colab.research.google.com/github/sai3601/intro_pandas/blob/main/pandas_intro_commands_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [37]:
df=pd.read_csv('Salaries.csv')

In [3]:
df

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [4]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [5]:
df.tail()

         rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [6]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [7]:
df.shape

(78, 6)

In [8]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

In [10]:
pd.set_option('display.max_rows', None)

In [11]:
df

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [12]:
df.isnull()

     rank  discipline    phd  service    sex  salary
0   False       False  False    False  False   False
1   False       False  False    False  False   False
2   False       False  False    False  False   False
3   False       False  False    False  False   False
4   False       False  False    False  False   False
5   False       False  False    False  False   False
6   False       False  False    False  False   False
7   False       False  False    False  False   False
8   False       False  False    False  False   False
9   False       False  False    False  False   False
10  False       False  False    False  False   False
11  False       False  False    False  False   False
12  False       False  False    False  False   False
13  False       False  False    False  False   False
14  False       False  False    False  False   False
15  False       False  False    False  False   False
16  False       False  False    False  False   False
17  False       False  False    False  False   False
18  False       False  False    False  False   False
19  False       False  False    False  False   False
20  False       False  False    False  False   False
21  False       False  False    False  False   False
22  False       False  False    False  False   False
23  False       False  False    False  False   False
24  False       False  False    False  False   False
25  False       False  False    False  False   False
26  False       False  False    False  False   False
27  False       False  False    False  False   False
28  False       False  False    False  False   False
29  False       False  False    False  False   False
30  False       False  False    False  False   False
31  False       False  False    False  False   False
32  False       False  False    False  False   False
33  False       False  False    False  False   False
34  False       False  False    False  False   False
35  False       False  False    False  False   False
36  False       False  False    False  False   False
37  False       False  False    False  False   False
38  False       False  False    False  False   False
39  False       False  False    False  False   False
40  False       False  False    False  False   False
41  False       False  False    False  False   False
42  False       False  False    False  False   False
43  False       False  False    False  False   False
44  False       False  False    False  False   False
45  False       False  False    False  False   False
46  False       False  False    False  False   False
47  False       False  False    False  False   False
48  False       False  False    False  False   False
49  False       False  False    False  False   False
50  False       False  False    False  False   False
51  False       False  False    False  False   False
52  False       False  False    False  False   False
53  False       False  False    False  False   False
54  False       False  False    False  False   False
55  False       False  False    False  False   False
56  False       False  False    False  False   False
57  False       False  False    False  False   False
58  False       False  False    False  False   False
59  False       False  False    False  False   False
60  False       False  False    False  False   False
61  False       False  False    False  False   False
62  False       False  False    False  False   False
63  False       False  False    False  False   False
64  False       False  False    False  False   False
65  False       False  False    False  False   False
66  False       False  False    False  False   False
67  False       False  False    False  False   False
68  False       False  False    False  False   False
69  False       False  False    False  False   False
70  False       False  False    False  False   False
71  False       False  False    False  False   False
72  False       False  False    False  False   False
73  False       False  False    False  False   False
74  False       False  False    False  False   False
75  False       False  False    False  False   False
76  False       False  False    False  False   False
77  False       False  False    False  False   False

In [13]:
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [14]:
df.describe(include='all')

        rank discipline        phd    service   sex         salary
count     78         78  78.000000  78.000000    78      78.000000
unique     3          2        NaN        NaN     2            NaN
top     Prof          B        NaN        NaN  Male            NaN
freq      46         42        NaN        NaN    39            NaN
mean     NaN        NaN  19.705128  15.051282   NaN  108023.782051
std      NaN        NaN  12.498425  12.139768   NaN   28293.661022
min      NaN        NaN   1.000000   0.000000   NaN   57800.000000
25%      NaN        NaN  10.250000   5.250000   NaN   88612.500000
50%      NaN        NaN  18.500000  14.500000   NaN  104671.000000
75%      NaN        NaN  27.750000  20.750000   NaN  126774.750000
max      NaN        NaN  56.000000  51.000000   NaN  186960.000000

In [15]:
df['rank'].value_counts()

rank
Prof         46
AsstProf     19
AssocProf    13
Name: count, dtype: int64

In [16]:
df.mean(numeric_only=True)

phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64

In [17]:
df['phd'].mean()

19.705128205128204

In [18]:
df['service'].mean()

15.051282051282051

In [19]:
df['salary'].mean()

108023.78205128205

In [20]:
df['phd'].median()

18.5

In [21]:
df['service'].median()

14.5

In [22]:
df['service'].median()

14.5

In [23]:
df["phd"].mode()

0    4
Name: phd, dtype: int64

In [24]:
df['service'].median()

14.5

In [25]:
df['salary'].mode()

0    92000
Name: salary, dtype: int64

In [26]:
df['salary'].mean()

108023.78205128205

In [27]:
df[['salary','service']].mean()

salary     108023.782051
service        15.051282
dtype: float64

In [28]:
df['phd'].var()

156.21062271062277

In [29]:
df['phd'].std()

12.498424809175866

In [30]:
df['phd'].skew()

0.6343660525514754

In [31]:
df['phd'].kurt()

0.042503564567506036

In [32]:
df['phd'].max()

56

In [33]:
df['phd'].min()

1

In [34]:
df['phd'].max()-df['phd'].min()

55

In [39]:
# prompt: can you import basic library pandas in this worktab

!pip install pandas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

55

In [44]:
# prompt: can you read this file and doand don't use exceptionalhandling/content//content/Salaries.csv

import pandas as pd

# Assuming Salaries.csv is in the current working directory or provide the full path
try:
    df = pd.read_csv('Salaries.csv')

    # Displaying some basic information about the DataFrame
    print(df.head())  # First 5 rows
    print(df.tail())  # Last 5 rows
    print(df.columns) # Column names
    print(df.shape)   # Number of rows and columns
    print(df.dtypes)  # Data types of each column
    print(df.info())  # Summary of the DataFrame

    # Descriptive statistics
    print(df.describe())  # Summary statistics for numerical columns
    print(df.describe(include='all'))  # Summary statistics for all columns

    # Value counts for 'rank'
    print(df['rank'].value_counts())

    # Mean values
    print(df.mean(numeric_only=True))
    print(df['phd'].mean())
    print(df['service'].mean())
    print(df['salary'].mean())

    # Other statistics
    print(df['phd'].median())
    print(df['service'].median())
    print(df["phd"].mode())
    print(df['salary'].mode())

    # Calculations on multiple columns
    print(df[['salary', 'service']].mean())
    print(df['phd'].var())
    print(df['phd'].std())
    print(df['phd'].skew())
    print(df['phd'].kurt())
    print(df['phd'].max())
    print(df['phd'].min())
    print(df['phd'].max() - df['phd'].min())
except FileNotFoundError:
    print("Error: 'Salaries.csv' not found. Please ensure the file is in the current directory or provide the correct path.")
except pd.errors.EmptyDataError:
    print("Error: 'Salaries.csv' is empty.")
except pd.errors.ParserError:
    print("Error: There was a problem parsing 'Salaries.csv'. Please check the file format.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800
         rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646
Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')
(78, 6)
rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB
None
             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000
        rank discipline        phd    service   sex         salary
count     78         78  78.000000  78.000000    78      78.000000
unique     3          2        NaN        NaN     2            NaN
top     Prof          B        NaN        NaN  Male            NaN
freq      46         42        NaN        NaN    39            NaN
mean     NaN        NaN  19.705128  15.051282   NaN  108023.782051
std      NaN        NaN  12.498425  12.139768   NaN   28293.661022
min      NaN        NaN   1.000000   0.000000   NaN   57800.000000
25%      NaN        NaN  10.250000   5.250000   NaN   88612.500000
50%      NaN        NaN  18.500000  14.500000   NaN  104671.000000
75%      NaN        NaN  27.750000  20.750000   NaN  126774.750000
max      NaN        NaN  56.000000  51.000000   NaN  186960.000000
rank
Prof         46
AsstProf     19
AssocProf    13
Name: count, dtype: int64
phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64
19.705128205128204
15.051282051282051
108023.78205128205
18.5
14.5
0    4
Name: phd, dtype: int64
0    92000
Name: salary, dtype: int64
salary     108023.782051
service        15.051282
dtype: float64
156.21062271062277
12.498424809175866
0.6343660525514754
0.042503564567506036
56
1
55

In [43]:
# prompt: can you use head function and first five in the dataset and don't use exceptional handling

import pandas as pd

df = pd.read_csv('Salaries.csv')
print(df.head())

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [45]:
df.iloc[:,:]

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [46]:
df.iloc[0:10,:]

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

In [47]:
df.iloc[0:10,:3]

        rank discipline  phd
0       Prof          B   56
1       Prof          A   12
2       Prof          A   23
3       Prof          A   40
4       Prof          B   20
5       Prof          A   20
6  AssocProf          A   20
7       Prof          A   18
8       Prof          A   29
9       Prof          A   51

In [49]:
# prompt: select first 10 records and first five columns from dataset

df.iloc[:10, :5]

        rank discipline  phd  service   sex
0       Prof          B   56       49  Male
1       Prof          A   12        6  Male
2       Prof          A   23       20  Male
3       Prof          A   40       31  Male
4       Prof          B   20       18  Male
5       Prof          A   20       20  Male
6  AssocProf          A   20       17  Male
7       Prof          A   18       18  Male
8       Prof          A   29       19  Male
9       Prof          A   51       51  Male

In [50]:
df.groupby('rank').mean(numeric_only=True)

                 phd    service         salary
rank
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [56]:
df.groupby('rank')[['salary','phd']].mean()

                  salary        phd
rank
AssocProf   91786.230769  15.076923
AsstProf    81362.789474   5.052632
Prof       123624.804348  27.065217